name: Automated release of new Specter versions

on: "repository_dispatch"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/cryptoadvance/specter-desktop.git
        id: specter

      - run: echo "Latest specter is ${{ steps.specter.outputs.tag }}"

      - uses: actions/checkout@v2

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.specter.outputs.tag }}
          message: "Latest specter release (automated tag)"
