name: Docker build on push
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on: push

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build and push all the stuff defined in this repo
                steps:
                        - name: Checkout repo
                          uses: actions/checkout@v2

                        - name: Set env variables
                          run: |
                                  echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
                                  echo "::set-env name=SHORTSHA::$(git rev-parse --short HEAD)"

                        - name: Show set env variables
                          run: |
                                  printf "    BRANCH: %s\n"  "$BRANCH"
                                  printf "    SHORTSHA: %s\n"  "$SHORTSHA"
                                  printf "    REPO: %s\n" "$GITHUB_REPOSITORY"
                                  printf "    COMMIT ID: %s\n" "$GITHUB_SHA"

                        - name: Login to Docker Hub
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

                        - name: Setup Docker buildx action
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest

                        - name: Show available Docker buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}

                        - name: Cache Docker layers
                          uses: actions/cache@v2
                          id: cache
                          with:
                              path: /tmp/.buildx-cache
                              key: ${{ runner.os }}-buildx-${{ github.sha }}
                              restore-keys: |
                                  ${{ runner.os }}-buildx-



